spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=UTC&useSSL=false
    username: root
    password: baejunbum10
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: key # application-key.yml 파일로 중요 키 분리
  servlet:
    multipart: # 파일 업로드 시 사이즈
      enabled: true
      max-file-size: 5MB # 5MB
      max-request-size: 5MB
  mvc:
    problemdetails:
      enabled: true # 응답에 detail error message 출력
  jpa:
    hibernate:
      ddl-auto: update   # create / create-drop / update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    sun.rmi: OFF
    sun.rmi.transport: OFF
    sun.rmi.transport.tcp: OFF
    sun.rmi.loader: OFF
    javax.management.remote: OFF
    javax.management.remote.rmi: OFF


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

frontend:
  host: http://localhost:3000

aws:
  s3:
    region: ap-southeast-2
    bucket: community-demo-bucket